### ISSUE TITLE
DISCUSSION: "Native" terraform usage

### ISSUE THREAD

**Issue by jrnt30** [nadnerb/terraform_exec#4]
Looking over the code (or the issues where this was brought up) you mentioned you may opt to try and package Terraform natively into terraform_exec to reduce the need to install two things. If I understood correctly, you were meaning the static compilation to be used in terraform exec.

From my perspective, this would be a misstep.  A few issues I would have with this is: 

* Terraform's dynamic build out of all the providers and resource providers makes for a rather large installation, where as terraform_exec can still remain small and lightweight 
* If I want to customize the version for local development or an organization's internal fork, I would need to recompile terraform_exec with it 

Overall looks like an interesting start to something that could be useful, just hope to see it stay "on point" in terms of it's true value add and not take on too much complexity for debatable functionality

**Comment by nadnerb** [comment]
Very true, thanks for the feedback :+1:

**Comment by jrnt30** [comment]
You're welcome, keep up the good work :)
